<a href="https://colab.research.google.com/github/marilynbgl/investigacionOperativa/blob/main/sesion1_27_09.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# INTRODUCCION A PROGRAMACION

## PRIMERA CLASE

#TIPO DE DATOS INTEGRADOS(PRIMITIVOS)


Tipo     |  Descripcion
---------|-----------------
string   | cadena de texto
int      | mumero entero
float    | numero real
bool     | booleano









In [ ]:
nom="alfredoos"
type(nom)

str

## ** operadores aritmeticos y opeardores logicos**


DESCRIPCION     | OPERADOR
----------------|----------
SUMA            |  +
DIFERENCIA      |  -
POTENCIA        | **
MODULO          | %
DISYUNCION      | or
CONJUNCION      | and
NEGACION        | not


# ** INSERCION DE CODIGO LATEX**

$\frac{a}{b+c}$

$x+y+\mathcal{T}$

## FUNCIONES INTEGRADAS**
complex que convierte a numero complejo
[ejemplo de link](https://)
pow = potencia
abs = absoluto


# FUNCIONES MATEMATICAS DEL MODULO MATH


## ** MODULO MATH**

In [ ]:
import math #carga el modulo de funciones math

In [ ]:
math.gcd(8,4) # saca el maximo comun divisor
math.exp(1) # funcion exponencial con base e

2.718281828459045

## Estructura de datos en python **

https://towardsdatascience.com/which-python-data-structure-should-you-use-fa1edd82946c)
<img src="https://miro.medium.com/max/1400/1*2JFd94q0vzsEcr-LB-220g.png

##LISTA **
Estructura que permte almacenar elementos de diferentes tipos.  

In [ ]:
lista1=[1,"jorge", True] # esto es un objeto de la estructra lista
print(type(lista1))
print(lista1[0])
print(lista1[1])
print(lista1[2])

<class 'list'>
1
jorge
True


In [ ]:
lista2=[255,"pepe",lista1] #lista dentro de lista
print(lista2[0])
print(lista2[1])
print(lista2[2][1]) # acccediendo al elemento con indice 1 dele elemento con indice 2 de la lista 2

255
pepe
jorge


## **METODOS Y FUNCIONES PARA LISTAS**

In [ ]:
#UN METODO ES UNA FUNCIÓN QUE "PERTENECE" A UN OBJETO
edades=[25,23,12,45,13,23]
edades.sort()
edades.sort(reverse=True) #invierte a descendente el orden
print(edades)
edades.append(100)
print(edades)
edades.sort()
print(edades)

[45, 25, 23, 23, 13, 12]
[45, 25, 23, 23, 13, 12, 100]
[12, 13, 23, 23, 25, 45, 100]


In [ ]:
edades.count(23) # el metodo count devuelve el número de ocurrencias de un objeto dentro de una lista


2

In [ ]:
edades2=[25,23,12,45,13,23]
edades3= sorted(edades2) #funcion "sorted" incorporada en python
print(edades2)
print(edades3)

[25, 23, 12, 45, 13, 23]
[12, 13, 23, 23, 25, 45]


In [ ]:
pesos=[20.5,33.0,12.3,18.7]
pesos.sort(reverse=True)
print(pesos)

[33.0, 20.5, 18.7, 12.3]


In [ ]:
poligonos=["triangulo","cuadrado", "trapecio"]
print(poligonos)
poligonos.append("rombo")
poligonos.reverse()
print(poligonos)

['triangulo', 'cuadrado', 'trapecio']
['rombo', 'trapecio', 'cuadrado', 'triangulo']


In [ ]:
otros=["hexagono","pentagono"]
poligonos.append(otros)
poligonos.insert(0,"rectangulo")
print(poligonos)

['rectangulo', 'rombo', 'trapecio', 'cuadrado', 'triangulo', ['hexagono', 'pentagono']]


In [ ]:
poligonos.remove("cuadrado")
print(poligonos)

['rectangulo', 'rombo', 'trapecio', 'triangulo', ['hexagono', 'pentagono']]


In [ ]:
len(poligonos)

5

In [ ]:
lista3=["a","b","c"]
lista4=["d","e"]
concat1= lista3+lista4
print(concat1)
concat2= lista4+lista3
print(concat2)

['a', 'b', 'c', 'd', 'e']
['d', 'e', 'a', 'b', 'c']


In [ ]:
print(lista3)
lista3[0]=123 #modificando la entrada 0 de lista3
print(lista3)

['a', 'b', 'c']
[123, 'b', 'c']


## TUPLA
estructura similar a la estructura lista, sin embargo es inmutable

In [ ]:
tupla=("a","b","c")
print(type(tupla))
print(tupla[0])
tupla.index("c")

<class 'tuple'>
a


2

In [ ]:
print("esto", tupla,"es una tupla\n")
tupla.index("b")


esto ('a', 'b', 'c') es una tupla



1

## RANGO
ESTRUCTURA PARA ALMACENAR SUCESIONES FINITS DE NUMEROS ENTEROS. ES INMUTABLE

In [ ]:
sucesion=range(7)
print(type(sucesion))
print(sucesion)
print(sucesion[0])
print(sucesion[1])
print(sucesion[2])
print("el objeto de la sucesion tiene",len(sucesion),"elementos")
rango=range(3,7)
print(rango)
print(rango[0])
print(rango[1])
print(rango[2])
print(rango[3])
print(rango.stop) #imprime el ultimo numero +1 ene este caso
rango=range(3,7,2)# el 2 indica la razon de aumento 2 en 2
print(rango)
print(rango[0])
print(rango[1])
#print(rango[2])
print(rango.stop) # imprime 7

<class 'range'>
range(0, 7)
0
1
2
el objeto de la sucesion tiene 7 elementos
range(3, 7)
3
4
5
6
7
range(3, 7, 2)
3
5
7


## MATRICES


In [ ]:
import numpy as np
m1=np.array([[5,0,1],[3,1,1],[0,1,2]])
print(m1)

matriz1 = np.array([[1., 2., 3.],[4., 5., 6.],[7.,8.,9.]])
print("Matriz original:\n", matriz1)
print(matriz1.dtype) # me da el tipo de datos que tiene mi matriz
matriz2= np.array([[1., 2., 3.],[4., 5., 6.]],dtype=np.float64)
transpuesta=matriz1.T
print(transpuesta)
traza=matriz1.trace()#hallando traza por medio de un objeto llamar su metodo
traza1=matriz1[0,0]+matriz1[1,1]+matriz1[2,2]
traza2=np.trace(matriz1)# de la libreria numpy tiene una funcion y se le debe poner el objeto a evaluar
print(traza, traza1, traza2)

[[5 0 1]
 [3 1 1]
 [0 1 2]]
Matriz original:
 [[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]
float64
[[1. 4. 7.]
 [2. 5. 8.]
 [3. 6. 9.]]
15.0 15.0 15.0


In [ ]:
sumMatriz= matriz1 + m1
print(sumMatriz)
matrizProducto=np.dot(matriz1,m1)
matrizPro2= np.matmul(matriz1,m1) #mas eficiente computacionalmente en costo
matrizPro3= matriz1 @ m1
print("matrizproducto= \n", matrizProducto, "\n matrizpro2=\n",matrizPro2,"\n matrizpro3=\n",matrizPro3 )
print(matriz1.dot(m1))

[[ 6.  2.  4.]
 [ 7.  6.  7.]
 [ 7.  9. 11.]]
matrizproducto= 
 [[11.  5.  9.]
 [35. 11. 21.]
 [59. 17. 33.]] 
 matrizpro2=
 [[11.  5.  9.]
 [35. 11. 21.]
 [59. 17. 33.]] 
 matrizpro3=
 [[11.  5.  9.]
 [35. 11. 21.]
 [59. 17. 33.]]
[[11.  5.  9.]
 [35. 11. 21.]
 [59. 17. 33.]]


In [ ]:
#ejercicio de la suma de matrices con codigo
import numpy as np

def suma(m1,m2):
    resultado = np.zeros_like(m1)

    for i in range(len(m1)):
       for j in range(len(m1[0])):
        resultado[i][j]=m1[i][j] + m2[i][j]
    return resultado

# Generar una matriz de nxn con enteros entre 0 y 9 (el 100 no está incluido)
a= int(input("ingresa el orden de la matriz:"))
matriz1 = np.random.randint(0, 100, size=(a, a))
matriz2 = np.random.randint(0,100,size=(a,a))
print("matriz 1:\n", matriz1)
print("matriz 2:\n", matriz2)
print("\n suma es:\n",suma(matriz1,matriz2))

ingresa el orden de la matriz:3
matriz 1:
 [[37 41 42]
 [59 43 74]
 [11 33 54]]
matriz 2:
 [[67 11  9]
 [50 63 47]
 [22 18 73]]

 suma es:
 [[104  52  51]
 [109 106 121]
 [ 33  51 127]]


In [ ]:
#ingresando datos para dos matrices y que tengan la misma dimension
import numpy as np

def suma(m1,m2):
    # Verifica si las matrices tienen las mismas dimensiones
    if len(m1) != len(m2) or len(m1[0]) != len(m2[0]):
        return "Error: Las matrices deben tener las mismas dimensiones para sumarse."
    resultado = np.zeros_like(m1)
    for i in range(len(m1)):
       for j in range(len(m1[0])):
        resultado[i][j]=m1[i][j] + m2[i][j]
    return resultado

# Generar una matriz de nxn con enteros entre 0 y 9 (el 100 no está incluido)
a= int(input("ingresa el numero de filas para matriz1:"))
b= int(input("ingresa el numero de columnas para matriz 1 :"))
c= int(input("ingresa el numero de filas para matriz 2:"))
d= int(input("ingresa el numero de columnas para matriz 2:"))
matriz1 = np.random.randint(0, 100, size=(a, b))
matriz2 = np.random.randint(0,100,size=(c,d))
#f= len(matriz1) #numero de filas de la matriz
#c= len(matriz1[0]) #numero de columnas de la matriz
#print("numero de filas:",f )
#print("numero de columnas:", c)
print("matriz 1:\n", matriz1)
#print("\n")
print("matriz 2:\n", matriz2)
print("\n suma es:\n",suma(matriz1,matriz2))

In [ ]:
vect2=np.linspace(2,6,7)
print(vect2)

mat2=np.random.rand(3,3)# llena matriz de datoas aleatorios
print(mat2)

mat3=np.empty((3,3),dtype=np.float32) #una matriz vacia con orden 3 de tipo de dato float32
print(mat3)
mat3[0][0]= np.pi
print(mat3)


[2.         2.66666667 3.33333333 4.         4.66666667 5.33333333
 6.        ]
[[0.22568394 0.6299442  0.13251652]
 [0.29198521 0.46893936 0.29682474]
 [0.66158661 0.62714303 0.48347218]]
[[ 3.1415927e+00  0.0000000e+00  0.0000000e+00]
 [ 0.0000000e+00  3.3292057e-34  0.0000000e+00]
 [-9.6386316e-08  4.3626625e-41  1.3228258e-42]]
[[ 3.1415927e+00  0.0000000e+00  0.0000000e+00]
 [ 0.0000000e+00  3.3292057e-34  0.0000000e+00]
 [-9.6386316e-08  4.3626625e-41  1.3228258e-42]]
